package org.apache.jsp.WEB_002dINF.memb.wenyao;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class pharmacist_005frecommend_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");


String path = request.getContextPath();
String templateUrl = request.getScheme() + "://" + request.getHeader("host") +request.getContextPath();
request.setAttribute("url", templateUrl);

String search_str=new String(request.getParameter("search_str").getBytes("iso8859-1"),"utf-8");
//String search_str=request.getParameter("search_str");
String searchSelect=new String(request.getParameter("searchSelect").getBytes("iso8859-1"),"utf-8");
//String mediId=new String(request.getParameter("mediId").getBytes("iso8859-1"),"utf-8"); 
String username =(String) session.getAttribute("username");


      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../include/core_head.jsp", out, false);
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"> \r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/css0623/expert_recommendation.css\"/>\r\n");
      out.write("<link rel='stylesheet' type=\"text/css\" href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/schedule/jquery-ui-1.11.4/jquery-ui.css' />\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/css0623/pagination.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/include/head.jsp", out, false);
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/js0623/jquery.pagination.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"  src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/schedule/jquery-ui-1.11.4/jquery-ui.js'></script>   <!-- 支付弹出窗口 -->\r\n");
      out.write("\r\n");
      out.write("<script charset=\"utf-8\"  type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("//筛选条件\r\n");
      out.write("\r\n");
      out.write("var tiaojian = {\r\n");
      out.write("\t\"currProvince\":\"\",\r\n");
      out.write("\t\"currZhicheng\":\"\",\r\n");
      out.write("\t\"search_str\":\"");
      out.print(search_str);
      out.write("\",\r\n");
      out.write("\t\"pageIndex\":0\r\n");
      out.write("} ;\r\n");
      out.write("\r\n");
      out.write("window.onload = function(){\r\n");
      out.write("\tif('");
      out.print(search_str);
      out.write("'!=\"\"){\r\n");
      out.write("\t\tbind(0);\r\n");
      out.write("\t\t$(\"#turnBg li\").removeClass(\"addBg\");\r\n");
      out.write("\t\t$(\"#turnBg li[id=choose2]\").attr(\"class\",\"addBg\");\r\n");
      out.write("\t\t$(\"#searchSelect\").val(\"");
      out.print(searchSelect);
      out.write("\");\r\n");
      out.write("\t}\r\n");
      out.write("\t$(\"#turnBg li\").each(function(){\r\n");
      out.write("\t\t$(this).click(function(){\r\n");
      out.write("\t\t$(this).siblings(\".addBg\").removeClass(\"addBg\");\r\n");
      out.write("\t\t$(this).attr(\"class\",\"addBg\");\r\n");
      out.write("\t\t$(\"#searchSelect\").val($(this).attr(\"value\"));\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t$(\"#searchIn\").find(\"input[type=button]\").click(function(){\r\n");
      out.write("\t\tvar item=$(\"#turnBg .addBg\").attr(\"value\");\r\n");
      out.write("\t\tif(item==\"qiuyi\"){\r\n");
      out.write("\t\t\t$('#searchIn').attr('action','MediKnow');\r\n");
      out.write("\t\t}else if(item==\"wenyao\"){\r\n");
      out.write("\t\t\t$('#searchIn').attr('action','SearchMedicine');\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$('#searchIn').attr('action','SearchRegimen');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif($('#search_str').val()=='')\r\n");
      out.write("\t\t\talert('请输入搜索词条！');\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t$('#searchIn').submit();}\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#intelligenBtn\").click(function(){\r\n");
      out.write("\t\tif($('#search_str').val()==\"失眠\"){\r\n");
      out.write("\t\t\t$(\"#intelligen\").attr(\"href\",\"intelligent_query?search_str=\" + $('#search_str').val()+\"&searchSelect=\"+$('#searchSelect').val());\r\n");
      out.write("\t\t\tdocument.getElementById(\"intelligen\").click();\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t    alert('目前只能咨询失眠');\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t  \r\n");
      out.write("\t});\r\n");
      out.write("\t$(\".expertsT a\").click(function(){\r\n");
      out.write("\t\tif($(this).parent().parent().attr(\"class\")==\"one\"){\r\n");
      out.write("\t\t\talert(\"yes\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif($(this).parent().parent().attr(\"class\")==\"two\"){\r\n");
      out.write("\t\t\ttiaojian.currProvince = $(this).text();\r\n");
      out.write("\t\t\t$(\".one .twoT\").remove();\r\n");
      out.write("\t\t\t$(\".one\").append(\"<span class=\\\"twoT\\\"><a onclick=\\\"deleteTiaoJian(this);\\\" href=\\\"javascript:void(0)\\\">\"+ $(this).text()+\"<img src=\\\"imgs/redX.jpg\\\" ></img></a></span>\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif($(this).parent().parent().attr(\"class\")==\"three\"){\r\n");
      out.write("\t\t\ttiaojian.currZhicheng = $(this).text();\r\n");
      out.write("\t\t\t$(\".one .threeT\").remove();\r\n");
      out.write("\t\t\t$(\".one\").append(\"<span class=\\\"threeT\\\"><a onclick=\\\"deleteTiaoJian(this);\\\" href=\\\"javascript:void(0)\\\">\"+ $(this).text()+\"<img src=\\\"imgs/redX.jpg\\\" ></img></a></span>\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tbind(0);\r\n");
      out.write("\t});\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("function  deleteTiaoJian(obj){\r\n");
      out.write("\tif($(obj).parent().attr(\"class\")==\"twoT\"){\r\n");
      out.write("\t\ttiaojian.currProvince = \"\";\r\n");
      out.write("\t}\r\n");
      out.write("\tif($(obj).parent().attr(\"class\")==\"threeT\"){\r\n");
      out.write("\t\ttiaojian.currZhicheng = \"\";\r\n");
      out.write("\t}\r\n");
      out.write("\t$(obj).parent().remove();\r\n");
      out.write("\tbind(0);\r\n");
      out.write("}\r\n");
      out.write("\t\r\n");
      out.write("function getProvince(currProvince){\r\n");
      out.write("\ttiaojian.currProvince = currProvince;\r\n");
      out.write("\t bind(0);\r\n");
      out.write("}\r\n");
      out.write("function getZhicheng(currZhicheng){\r\n");
      out.write("\ttiaojian.currZhicheng = currZhicheng;\r\n");
      out.write("    bind(0);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function pageselectCallback(page_id,jq){\r\n");
      out.write("    bind(page_id);\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function bind(pageIndex){\r\n");
      out.write("\t//alert($('#input_doctor').val());\r\n");
      out.write("\t//alert(\"sd\");\r\n");
      out.write("  var total = 0;\r\n");
      out.write("  tiaojian.pageIndex = (pageIndex+1);\r\n");
      out.write("  \r\n");
      out.write("  $.ajax({\r\n");
      out.write("    url : '");
      out.print(templateUrl);
      out.write("/PharmacistAction',\r\n");
      out.write("    type : 'POST',\r\n");
      out.write("    data: JSON.stringify(tiaojian),\r\n");
      out.write("    contentType: \"application/json; charset=utf-8\", \r\n");
      out.write("\tdataType : 'json',\r\n");
      out.write("\ttimeout : 15000,\r\n");
      out.write("\tcache : true,\r\n");
      out.write("\tbeforeSend : LoadFunction, //加载执行方法  \r\n");
      out.write("\terror : erryFunction, //错误执行方法  \r\n");
      out.write("\tcomplete : conFunction,\r\n");
      out.write("\tsuccess : succFunction\r\n");
      out.write("\t\t\t//成功执行方法  \r\n");
      out.write("\t});\r\n");
      out.write("\tfunction LoadFunction() {\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction erryFunction() {\r\n");
      out.write("\t   alert(\"请刷新页面\");\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction conFunction() {\r\n");
      out.write("\t\t;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction succFunction(data) {\r\n");
      out.write("\t    //alert(\"success\");\r\n");
      out.write("\t    $(\"#doctor_list\").html(\"\");\r\n");
      out.write("\t    var total = data.account;\r\n");
      out.write("\t    $(\".doctorCon li\").remove();\r\n");
      out.write("\t    if(total==0){\r\n");
      out.write("\t    \t$(\"#doctor_list\").html($(\"#doctor_list\").html()+\"<p>\"+data.nullInfo+\"</p>\");\r\n");
      out.write("\t    }\r\n");
      out.write("\t    else{\r\n");
      out.write("\t    \t $.each(data.pharmacistArray, function(index) {\r\n");
      out.write("\t    \t\tvar s1 = \"<li><img src=\\\"imgs/man_3.png\\\"/><div class=\\\"doctorMess\\\">\";\r\n");
      out.write("\t \t    \tvar s2 = \"<p class=\\\"doctorName\\\">\"+data.pharmacistArray[index].pharmacistName+\"</p><p class=\\\"doctorMess2\\\"><span>[职称] </span>\"+data.pharmacistArray[index].zhicheng+\"</p><p class=\\\"doctorMess2\\\"><span>[医院] </span>\"+data.pharmacistArray[index].yiyuan+\"</p><p class=\\\"doctorMess2\\\"><span>[科室] </span>\"+data.pharmacistArray[index].keshi+\"</p></div>\";\r\n");
      out.write("\t \t    \tvar s3 =\"<span class=\\\"doctorInter\\\"></span><div class=\\\"doctorMiddle\\\"><p class=\\\"doctorMess2\\\"><span>[擅长] </span></p><p class=\\\"doctorMess22\\\">\"+data.pharmacistArray[index].good+\"</p></div><span class=\\\"doctorInter\\\"></span><div class=\\\"doctorMore\\\"><div class=\\\"doctorMoreText\\\">\";\r\n");
      out.write("\t \t    \tvar s4 =\"<span class=\\\"one\\\" onclick=\\\"javascript:payDialog2(this,'\"+data.pharmacistArray[index].pharmacistId+\"','\"+data.pharmacistArray[index].pharmacistName+\"');\\\"></span>\";\r\n");
      out.write("\t \t    \tvar s5 =\"<span class=\\\"two\\\" onclick=\\\"javascript:payDialog(this,'\"+data.pharmacistArray[index].pharmacistId+\"','\"+data.pharmacistArray[index].pharmacistName+\"');\\\"></span>\";\r\n");
      out.write("\t \t    \tvar s6 =\"<span class=\\\"three\\\" onclick=\\\"javascript:appointMentExpert(this,'\"+data.pharmacistArray[index].pharmacistId+\"','\"+data.pharmacistArray[index].pharmacistName+\"');\\\"></span>\";\r\n");
      out.write("\t \t    \tvar s7 =\"<span class=\\\"four\\\" onclick=\\\"javascript:collectExpert(this,'\"+data.pharmacistArray[index].pharmacistId+\"');\\\"></span></div></div></li>\";\r\n");
      out.write("\t \t    \t$(\".doctorCon\").append(s1+s2+s3+s4+s5+s6+s7);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t    \t \r\n");
      out.write("\t    \tif('");
      out.print(username);
      out.write("'=='null'){\r\n");
      out.write("\t\t\t\t $(\".doctorMoreText span\").each(function(index){\r\n");
      out.write("\t\t\t\t\t $(this).attr(\"onclick\",\"javascript:alert('请先登录')\");\r\n");
      out.write("\t\t\t\t\t $(this).attr(\"href\");\r\n");
      out.write("\t\t\t\t });\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t    \t \r\n");
      out.write("\t    \t $('#Pagination').pagination(total,{ //recordCount在后台定义的一个公有变量，通过从数据库查询记录进行赋值，返回记录的总数\r\n");
      out.write("\t  \t        recordCount: total,   \r\n");
      out.write("\t              callback: pageselectCallback,  //点击分页时，调用的回调函数  \r\n");
      out.write("\t              prev_text: '« 上一页',  //显示上一页按钮的文本  \r\n");
      out.write("\t              next_text: '下一页 »',  //显示下一页按钮的文本  \r\n");
      out.write("\t              items_per_page:4,  //每页显示的项数  \r\n");
      out.write("\t              num_display_entries:14,  //分页插件中间显示的按钮数目  \r\n");
      out.write("\t              current_page:pageIndex,  //当前页索引  \r\n");
      out.write("\t              num_edge_entries:2 //分页插件左右两边显示的按钮数目  \r\n");
      out.write("\t          });  \r\n");
      out.write("\t    \t\r\n");
      out.write("\t    }\r\n");
      out.write("\t  \r\n");
      out.write("   }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//预约\r\n");
      out.write("function appointMentExpert(self,doctorId,doctorName){\r\n");
      out.write("\tif('");
      out.print(username);
      out.write("'=='null'){\r\n");
      out.write("\t\t $(this).attr(\"onclick\",\"javascript:alert('请先登录')\");\r\n");
      out.write("\t\t $(this).attr(\"href\");\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tvar s=\"user/yuyue?doctorId=\"+doctorId+\"&doctorName=\"+doctorName;\r\n");
      out.write("\t\twindow.open(\"");
      out.print(templateUrl);
      out.write("/\"+s);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//收藏\r\n");
      out.write("function collectExpert(collect,expeId){\r\n");
      out.write("\tvar  collectData=\"收藏\";\r\n");
      out.write("\t $.ajax({\r\n");
      out.write("         url : '");
      out.print(templateUrl);
      out.write("/CollectAction?collect='+collectData+'&userId='+expeId,\r\n");
      out.write("         type : 'POST',\r\n");
      out.write("         contentType: \"application/x-www-form-urlencoded; charset=utf-8\", \r\n");
      out.write("\t\t dataType : 'text',\r\n");
      out.write("\t\t timeout : 18000,\r\n");
      out.write("\t\t cache : true,\r\n");
      out.write("    \t error : erryFunction, //错误执行方法  \r\n");
      out.write("\t\t success : succFunction\t//成功执行方法  \r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tfunction erryFunction() {alert(\"收藏失败，请重试!!\");}\r\n");
      out.write("\t\tfunction succFunction(data) {\r\n");
      out.write("\t\t\tvar data = String($.trim(data)); \r\n");
      out.write("\t\t\tif(data=='yes'){\r\n");
      out.write("\t\t\t\talert(\"收藏成功!\");\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\talert(\"收藏失败，请重试!!\");\r\n");
      out.write("\t\t\t}\t\r\n");
      out.write("\t\t};\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\tfunction payDialog(self,id,name){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#dialog\").dialog(\"open\");\r\n");
      out.write("\t\t$(\"#confirm_consult\").click(function(){\r\n");
      out.write("\t\tvar s=\"user/payAction?userId=");
      out.print(username);
      out.write("&searchSelect=");
      out.print(searchSelect);
      out.write("&expe_id=\"+id+\"&expe_name=\"+name+\"\";\r\n");
      out.write("\t\twindow.open(\"");
      out.print(templateUrl);
      out.write("/\"+s);\r\n");
      out.write("\t\t$(\"#dialog\").dialog(\"close\");       //确认咨询后关闭对话框\r\n");
      out.write("\t\twindow.location.reload(true);   //关闭支付窗口后重新刷新一下页面！！！\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction payDialog2(self,id,name){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#dialog\").dialog(\"open\");\r\n");
      out.write("\t\t$(\"#confirm_consult\").click(function(){\r\n");
      out.write("\t\tvar s=\"user/payAction2?userId=");
      out.print(username);
      out.write("&searchSelect=");
      out.print(searchSelect);
      out.write("&expe_id=\"+id+\"&expe_name=\"+name+\"\";\r\n");
      out.write("\t\twindow.open(\"");
      out.print(templateUrl);
      out.write("/\"+s);\r\n");
      out.write("\t\t$(\"#dialog\").dialog(\"close\");       //确认咨询后关闭对话框\r\n");
      out.write("\t\twindow.location.reload(true);   //关闭支付窗口后重新刷新一下页面！！！\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t$(window).load(function(){\r\n");
      out.write("        \r\n");
      out.write("\t\t$(\"#dialog\").dialog({\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t  open:function(){//对话框打开时初始化\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tgetMemberCredit();\r\n");
      out.write("\t\t\t  },\r\n");
      out.write("\t\t    autoOpen: false,\r\n");
      out.write("\t\t    height:400,\r\n");
      out.write("\t\t    width:500,\r\n");
      out.write("\t\t    modal:true,\r\n");
      out.write("\t\t    title:'支付界面',\r\n");
      out.write("\t\t    draggable:true,\r\n");
      out.write("\t\t    buttons:[{\r\n");
      out.write("\t\t    text:\"关闭\",\r\n");
      out.write("\t\t    click:function(){\r\n");
      out.write("\t\t       $(this).dialog(\"close\");\r\n");
      out.write("\t\t       window.location.reload(true);   //关闭支付窗口后重新刷新一下页面！！！\r\n");
      out.write("\t\t     }\r\n");
      out.write("\t\t   }]\r\n");
      out.write("\t\t  });\t\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tfunction getMemberCredit(){\r\n");
      out.write("\t\tvar sss='");
      out.print(username);
      out.write("';\r\n");
      out.write("\t    $.ajax({\r\n");
      out.write("\t        url : '");
      out.print(templateUrl);
      out.write("/getMemberCreditValue?userId=");
      out.print(username);
      out.write("',\r\n");
      out.write("\t\t\ttype : 'POST',\r\n");
      out.write("\t\t\tcontentType : \"application/json; charset=utf-8\",\r\n");
      out.write("\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\ttimeout : 10000,\r\n");
      out.write("\t\t\tcache : true,\r\n");
      out.write("\t\t\terror : erryFunction, //错误执行方法  \r\n");
      out.write("\t\t\tsuccess : succFunction\r\n");
      out.write("\t\t//成功执行方法  \r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tfunction erryFunction() {\r\n");
      out.write("\t\t\talert(\"有错误，请刷新页面\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction succFunction(data) {\r\n");
      out.write("\t\t\t//未读消息条数\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar credit = data.credit;\r\n");
      out.write("\t\t\t$(\"#remainCredit\").html(credit);\r\n");
      out.write("\t\t\tif(credit<10){\r\n");
      out.write("\t\t\t  alert(\"您的积分不足，请先去积分中心充值！\");\r\n");
      out.write("\t\t\t  // 为什么用命名空间不可以 user/user-center\r\n");
      out.write("\t\t\t  window.location.href=\"");
      out.print(templateUrl);
      out.write("/user/user-center\";\r\n");
      out.write("\t\t\t  }\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\t\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("<title>药师列表</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<!--顶部背景-->\r\n");
      out.write("\t<div class=\"topCon\">\r\n");
      out.write("\t\t<img class=\"bg-01\" src=\"imgs/bg-01.jpg\"/>\r\n");
      out.write("\t\t<span class=\"headerBg\"></span>\r\n");
      out.write("\t\t<!--内容-->\r\n");
      out.write("\t\t<div class=\"indexCon\">\r\n");
      out.write("\t\t\t<a href=\"welcome\"><img class=\"logo\" src=\"imgs/logo.png\"/></a>\r\n");
      out.write("\t\t\t<p class=\"callCen\">\r\n");
      out.write("\t\t\t\t健康咨询平台\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<ul>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/include/topbar.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!--切换-->\r\n");
      out.write("\t\t<div class=\"indexFind\">\r\n");
      out.write("\t\t\t<ul id=\"turnBg\">\r\n");
      out.write("\t\t\t\t<li id=\"choose1\" value=\"qiuyi\">\r\n");
      out.write("\t\t\t\t\t<div id=\"choose1\" class=\"con\">\r\n");
      out.write("\t\t\t\t\t\t<img id=\"choose1\" class=\"top\" src=\"imgs/nav_braceTop.png\"/>\r\n");
      out.write("\t\t\t\t\t\t<span id=\"choose1\">求医</span>\r\n");
      out.write("\t\t\t\t\t\t<img  id=\"choose1\" class=\"bottom\" src=\"imgs/nav_bracebottom.png\"/>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li id=\"choose2\" value=\"wenyao\">\r\n");
      out.write("\t\t\t\t\t<div class=\"con\" id=\"choose2\">\r\n");
      out.write("\t\t\t\t\t\t<img id=\"choose2\" class=\"top\" src=\"imgs/nav_braceTop.png\"/>\r\n");
      out.write("\t\t\t\t\t\t<span id=\"choose2\">问药</span>\r\n");
      out.write("\t\t\t\t\t\t<img id=\"choose2\" class=\"bottom\" src=\"imgs/nav_bracebottom.png\"/>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li id=\"choose3\" value=\"yangsheng\">\r\n");
      out.write("\t\t\t\t\t<div id=\"choose3\" class=\"con\" >\r\n");
      out.write("\t\t\t\t\t\t<img id=\"choose3\" class=\"top\" src=\"imgs/nav_braceTop.png\"/>\r\n");
      out.write("\t\t\t\t\t\t<span id=\"choose3\">养生</span>\r\n");
      out.write("\t\t\t\t\t\t<img id=\"choose3\" class=\"bottom\" src=\"imgs/nav_bracebottom.png\"/>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--搜索-->\r\n");
      out.write("\t\t<form  method=\"get\" id=\"searchIn\">\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"search_str\" id=\"search_str\" value=\"");
      out.print(search_str);
      out.write("\"/>\r\n");
      out.write("\t\t\t<input type=\"hidden\" name = \"searchSelect\" value=\"wenyao\" id=\"searchSelect\"/>\r\n");
      out.write("\t\t\t<input type=\"button\" value=\"搜索\"/>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!--选药-->\r\n");
      out.write("\t<div class=\"chooseMidi\">\r\n");
      out.write("\t\t<ul class=\"midiTab\">\r\n");
      out.write("\t\t\t<li id=\"expert_recommendBtn\"  class=\"addBg\">\r\n");
      out.write("\t\t\t\t<div class=\"con\">\r\n");
      out.write("\t\t\t\t\t<span class=\"left\">专家</span>\r\n");
      out.write("\t\t\t\t\t<span class=\"right\">推荐</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li id=\"intelligenBtn\" >\r\n");
      out.write("\t\t\t\t<div class=\"con\">\r\n");
      out.write("\t\t\t\t\t<span class=\"left\">智能</span>\r\n");
      out.write("\t\t\t\t\t<span class=\"right\">咨询</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<a target=\"_blank\" id=\"intelligen\" style=\"display: none\"></a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<ul class=\"expertsT\">\r\n");
      out.write("\t\t\t<li class=\"one\">\r\n");
      out.write("\t\t\t\t<img class=\"left\" src=\"imgs/paixu_3.png\"/>\r\n");
      out.write("\t\t\t\t<p>已选:</p>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li class=\"two\">\r\n");
      out.write("\t\t\t\t<img class=\"left\" src=\"imgs/diqu_3.png\"/>\r\n");
      out.write("\t\t\t\t<p>地区:</p>\r\n");
      out.write("\t\t\t\t<span><a href=\"javascript:void(0)\">北京</a></span>\r\n");
      out.write("\t\t\t\t<span><a href=\"javascript:void(0)\">湖南</a></span>\r\n");
      out.write("\t\t\t\t<span><a href=\"javascript:void(0)\">河南</a></span>\r\n");
      out.write("\t\t\t\t<span><a href=\"javascript:void(0)\">上海</a></span>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li class=\"three\">\r\n");
      out.write("\t\t\t\t<img class=\"left\" src=\"imgs/zhichen_3.png\"/>\r\n");
      out.write("\t\t\t\t<p>职称:</p>\r\n");
      out.write("\t\t\t\t <span><a href=\"javascript:void(0)\">主任药师</a></span>\r\n");
      out.write("\t\t\t\t <span><a href=\"javascript:void(0)\">副主任药师</a></span>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<span class=\"doctorTopPic\"></span>\r\n");
      out.write("\t\t<ul class=\"doctorCon\">\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<div id=\"Pagination\" class=\"megas512\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"dialog\" style=\"display: none\">\r\n");
      out.write("\t\t<div class=\"user_center_bigtitle\" style=\"text-align:center\">\r\n");
      out.write("\t\t\t<span>支付窗口</span>\r\n");
      out.write("\t\t\t<hr></hr>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"my_dis_diray\">\r\n");
      out.write("\t\t\t<div class=\"my_dis_diray_con\">\r\n");
      out.write("\t\t\t\t<div class=\"mg_info\"\r\n");
      out.write("\t\t\t\t\tstyle=\"font-family: '宋体';font-size: 18px;\">\r\n");
      out.write("\t\t\t\t\t<h3 style=\"text-align:center\">\r\n");
      out.write("\t\t\t\t\t\t您目前还剩积分:<a id=\"remainCredit\" href=\"javascript:void(0)\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"text-decoration:none\">0</a>\r\n");
      out.write("\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t<h3 style=\"text-align:center\">本次咨询需要10个积分</h3>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div style=\"margin-top:50px;margin-left:300px\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" id=\"confirm_consult\" name=\"confirm_consult\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"确认咨询\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/include/login.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
