package org.apache.jsp.WEB_002dINF.expe;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class DoctorOfflineConsultForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/core_head.jsp", out, false);
      out.write('\r');
      out.write('\n');

	String templateUrl = request.getScheme() + "://"
			+ request.getHeader("host") + request.getContextPath();
	request.setAttribute("url", templateUrl);
	//String expe_id=request.getParameter("doctorName");   //获取的不是专家ID；
	//String expe_id = new String(request.getParameter("doctorName").getBytes("iso8859-1"), "utf-8");
	//电子病历，唯一标识
	String electronic_record = request
			.getParameter("electronic_record");
	// out.println(expe_id);

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, (java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}/include/topbarhead.jsp", java.lang.String.class, (PageContext)_jspx_page_context, null, false), out, false);
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/css/article.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/css/tab02.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/css/style.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/css/jquery.autocomplete.css\" />\r\n");
      out.write("<link rel='stylesheet' href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/schedule/jquery-ui-1.11.4/jquery-ui.css' />\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/js/jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"  src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/schedule/jquery-ui-1.11.4/jquery-ui.js'></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/js/jquery.validate.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/js/register.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/css/main.css\" />\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>待处理离线咨询</title>\r\n");
      out.write("</head>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write(" function split( val ) {\r\n");
      out.write("      return val.split( /,\\s*/ );\r\n");
      out.write("    }\r\n");
      out.write("    function extractLast( term ) {\r\n");
      out.write("      return split( term ).pop();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("function checkSubmit(){\r\n");
      out.write("\tif($('#medical_result').val()==\"\"){\r\n");
      out.write("\t\t$(\"#medical_result\").select();\r\n");
      out.write("\t\t$(\"#medical_result\").focus();\r\n");
      out.write("\t}else if($('#medical_advice').val()==\"\"){\r\n");
      out.write("\t\t$(\"#medical_advice\").select();\r\n");
      out.write("\t\t$(\"#medical_advice\").focus();\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\t//提交已处理的表单\r\n");
      out.write("\t\t//$(\"#DoctorofflineConsult\").submit();\r\n");
      out.write("\t\tsubmit();\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function submit(){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("        url : '");
      out.print(templateUrl);
      out.write("/expe/DoctorOfflineConsultAction',\r\n");
      out.write("\t\ttype : 'POST',\r\n");
      out.write("\t\tdata:\"electronic_record=");
      out.print(electronic_record);
      out.write("&MidecalZheng=\"+$('#second').val()+\"&medical_result=\"+$('medical_result').val()+\"&medical_advice\"+$('#medical_advice').val(),\r\n");
      out.write("\t\tcontentType: \"application/x-www-form-urlencoded; charset=utf-8\", \r\n");
      out.write("\t\tdataType : 'text',\r\n");
      out.write("\t\ttimeout : 8000,\r\n");
      out.write("\t\tcache : true,\r\n");
      out.write("\t\terrot:erryFunction,\r\n");
      out.write("\t\tsuccess : succFunction\r\n");
      out.write("\t//成功执行方法  \r\n");
      out.write("\t});\r\n");
      out.write("\tfunction erryFunction() {\r\n");
      out.write("\t\talert(\"请刷新页面！\");\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction succFunction(data) {\r\n");
      out.write("\t\tvar data = String($.trim(data)); \r\n");
      out.write("\t\tif(data==\"yes\"){\r\n");
      out.write("     \t\talert(\"提交成功!页面即将关闭\");\r\n");
      out.write("\t     \twindow.close();\r\n");
      out.write("\t    }else{\r\n");
      out.write("\t    \t alert(\"请重新操作！\");\r\n");
      out.write("\t   }\r\n");
      out.write("\t\t//window.location=\"diaryMan\";\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//获得辩证\r\n");
      out.write("function getMidecalZheng(data){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("        url : '");
      out.print(templateUrl);
      out.write("/expe/MidecalZhengAction?midecalZheng='+data,\r\n");
      out.write("        type : 'POST',\r\n");
      out.write("        contentType: \"application/x-www-form-urlencoded; charset=utf-8\", \r\n");
      out.write("\t\t dataType : 'json',\r\n");
      out.write("\t\t timeout : 3000,\r\n");
      out.write("\t\t cache : true,\r\n");
      out.write("\t\t error : erryFunction, //错误执行方法  \r\n");
      out.write("\t\t success : succFunction\t//成功执行方法  \r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tfunction erryFunction() {alert(\"请刷新页面！\");}\r\n");
      out.write("\t\tfunction succFunction(data) {\r\n");
      out.write("\t\t\t//alert(\"sdaf\");\r\n");
      out.write("\t\t\tvar ar=new Array();\r\n");
      out.write("\t\t\t$.each(data.MidecalZhengArray,function(index){\r\n");
      out.write("\t\t\t\tar[index]=data.MidecalZhengArray[index].name;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#suggest1\")\r\n");
      out.write("\t\t\t.bind(\"keydown\",function(event){\r\n");
      out.write("\t\t\tif(event.keyCode==$.ui.keyCode.TAB &&\r\n");
      out.write("\t\t\t$(this).data(\"ui-autocomplete\").menu.active){\r\n");
      out.write("\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t.autocomplete({\r\n");
      out.write("\t\t\tsource:function(request, response){\r\n");
      out.write("\t\t\tresponse( $.ui.autocomplete.filter(\r\n");
      out.write("            ar, extractLast( request.term ) ) );\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tminLength: 0,\r\n");
      out.write("\t\t\tfocus: function() {\r\n");
      out.write("          // 防止在获得焦点时插入值\r\n");
      out.write("          return false;\r\n");
      out.write("        \t}, \r\n");
      out.write("        select: function( event, ui ) {\r\n");
      out.write("          var terms = split( this.value );\r\n");
      out.write("          // 移除当前输入\r\n");
      out.write("          terms.pop();\r\n");
      out.write("          // 添加被选项\r\n");
      out.write("          terms.push( ui.item.value );\r\n");
      out.write("          // 添加占位符，在结尾添加逗号+空格\r\n");
      out.write("          terms.push( \"\" );\r\n");
      out.write("          this.value = terms.join( \", \" );\r\n");
      out.write("          return false;\r\n");
      out.write("        }\r\n");
      out.write("\t\t\t});\r\n");
      out.write("// \t\t\t$(\"#suggest1\").bind(\"input.autocomplete\",function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("// \t\t\t$(this).autocomplete(\"search\",this.value);\r\n");
      out.write("// \t\t\t});\r\n");
      out.write("\t};\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//获得辨病\r\n");
      out.write("function getMidecalDisease(data){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("        url : '");
      out.print(templateUrl);
      out.write("/expe/MidecalDiseaseAction?midecalDisease='+data,\r\n");
      out.write("        type : 'POST',\r\n");
      out.write("        contentType: \"application/x-www-form-urlencoded; charset=utf-8\", \r\n");
      out.write("\t\t dataType : 'json',\r\n");
      out.write("\t\t timeout : 3000,\r\n");
      out.write("\t\t cache : true,\r\n");
      out.write("\t\t error : erryFunction, //错误执行方法  \r\n");
      out.write("\t\t success : succFunction\t//成功执行方法  \r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tfunction erryFunction() {alert(\"请刷新页面！\");}\r\n");
      out.write("\t\tfunction succFunction(data) {\r\n");
      out.write("\t\t\talert(\"sdaf\");\r\n");
      out.write("\t\t\tvar ar=new Array();\r\n");
      out.write("\t\t\t$.each(data.MidecalDiseaseArray,function(index){\r\n");
      out.write("\t\t\t\tar[index]=data.MidecalDiseaseArray[index].name;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#suggest2\")\r\n");
      out.write("\t\t\t.bind(\"keydown\",function(event){\r\n");
      out.write("\t\t\tif(event.keyCode==$.ui.keyCode.TAB &&\r\n");
      out.write("\t\t\t$(this).data(\"ui-autocomplete\").menu.active){\r\n");
      out.write("\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t.autocomplete({\r\n");
      out.write("\t\t\tsource:function(request, response){\r\n");
      out.write("\t\t\tresponse( $.ui.autocomplete.filter(\r\n");
      out.write("            ar, extractLast( request.term ) ) );\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tminLength: 0,\r\n");
      out.write("\t\t\tfocus: function() {\r\n");
      out.write("          \t// 防止在获得焦点时插入值\r\n");
      out.write("          \treturn false;\r\n");
      out.write("        \t}, \r\n");
      out.write("        \tselect: function( event, ui ) {\r\n");
      out.write("         \t var terms = split( this.value );\r\n");
      out.write("\t          // 移除当前输入\r\n");
      out.write("\t          terms.pop();\r\n");
      out.write("\t          // 添加被选项\r\n");
      out.write("\t          terms.push( ui.item.value );\r\n");
      out.write("\t          // 添加占位符，在结尾添加逗号+空格\r\n");
      out.write("\t          terms.push( \"\" );\r\n");
      out.write("\t          this.value = terms.join( \", \" );\r\n");
      out.write("\t          return false;\r\n");
      out.write("       \t\t }\r\n");
      out.write("\t\t\t});\r\n");
      out.write("// \t\t\t$(\"#suggest2\").bind(\"input.autocomplete\",function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("// \t\t\t$(this).autocomplete(\"search\",this.value);\r\n");
      out.write("// \t\t\t});\r\n");
      out.write("\t};\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//获取电子病历表\r\n");
      out.write("function getElectronic_record(electronic_record){\r\n");
      out.write("\t $.ajax({\r\n");
      out.write("            url : '");
      out.print(templateUrl);
      out.write("/expe/ElectronicRecordAction?electronic_record=");
      out.print(electronic_record);
      out.write("',\r\n");
      out.write("\t\t\ttype : 'POST',\r\n");
      out.write("\t\t\tcontentType : \"application/x-www-form-urlencoded; charset=utf-8\",\r\n");
      out.write("\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\ttimeout : 5000,\r\n");
      out.write("\t\t\tcache : true,\r\n");
      out.write("\t\t\terror : erryFunction, //错误执行方法  \r\n");
      out.write("\t\t\tsuccess : succFunction\r\n");
      out.write("\t\t\t\t//成功执行方法  \r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\tfunction erryFunction() {\r\n");
      out.write("\t\t\talert(\"请刷新页面！\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction succFunction(data) {\r\n");
      out.write("\t\t\t$(\"#username\").html(data.userId);\r\n");
      out.write("\t\t\t$('#illn_desc').val(data.illn_desc);\r\n");
      out.write("\t\t\t$('#fami_hist').val(data.fami_hist);\r\n");
      out.write("\t\t\t$('#pers_hist').val(data.pers_hist);\r\n");
      out.write("\t\t\tif(parseInt(data.fileAccount)!=0){\r\n");
      out.write("\t\t\t\t$(\"#fileList\").html(\"附件：\");\r\n");
      out.write("\t\t\t\t$.each(data.file, function(index) {\r\n");
      out.write("\t\t\t\t\t//alert(index);\r\n");
      out.write("\t\t\t\t\t$(\"#fileList\").append(\"<li><a target=\\\"_blank\\\" href='FileDownloadAction?fileNumber=\"+index+\"&fileName=\"+data.file[index].fileName+\"&electronic_record=\"+'");
      out.print(electronic_record);
      out.write("'+\"'>\"+data.file[index].fileName+\"</a></li>\");\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("function getToolBoxList(){\r\n");
      out.write("\t  // var data=encodeURIComponent(JSON.stringify($('#input_doctor').val()),\"utf-8\");\r\n");
      out.write("\t  // alert(encodeURI(encodeURI($('#input_doctor').val())));//验证是否在线\r\n");
      out.write("\t    $.ajax({\r\n");
      out.write("\t        url : '");
      out.print(templateUrl);
      out.write("/expe/ToolBoxListAction',\r\n");
      out.write("\t\t\ttype : 'POST',\r\n");
      out.write("\t\t\tcontentType : \"application/json; charset=utf-8\",\r\n");
      out.write("\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\ttimeout : 10000,\r\n");
      out.write("\t\t\tcache : true,\r\n");
      out.write("\t\t\terror : erryFunction, //错误执行方法  \r\n");
      out.write("\t\t\tsuccess : succFunction\r\n");
      out.write("\t\t//成功执行方法  \r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tfunction erryFunction() {\r\n");
      out.write("\t\t\talert(\"有错误，请刷新页面\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction succFunction(data) {\r\n");
      out.write("\t\t\t//未读消息条数\r\n");
      out.write("\t\t\tvar num = data.acount;\r\n");
      out.write("\t\t\t//alert(num);\r\n");
      out.write("\t\t\t$(\"#toolBoxList\").children().remove();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#recAID\").html(num);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(parseInt(data.acount)!=0){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar th=$(\"<tr> <th>序号</th><th>方名</th><th>适应证</th><th>&nbsp</th></tr>\");\r\n");
      out.write("\t\t\t\tth.appendTo(\"#toolBoxList\");\r\n");
      out.write("\t\t\t\t$.each(data.ToolboxArray,function(index) {\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t//alert(data.OfflineConsultArray[index].electronic_record);\r\n");
      out.write("\t\t\t\t\tvar s1 = \"<tr><td>\"+(index+1)+\"</td>\"  ;\r\n");
      out.write("\t\t\t\t\tvar s2 = \"<td class=\\\"offAccount\\\"><a target=\\\"_blank\\\" href='expe/OpenToolBox?ToolBox_Id=\"+data.ToolboxArray[index].ToolBox_Id+\"'>\"+data.ToolboxArray[index].title+\"</a></td>\";\r\n");
      out.write("\t\t\t\t\tvar s3= \"<td>\"+data.ToolboxArray[index].syndrome+\"</td>\";\r\n");
      out.write("\t\t\t\t\t//var s4=\"<td>添加</td></tr>\";\r\n");
      out.write("\t\t\t\t\t//var s5= \"<td class=\\\"offAccount\\\"><a title=\\\"修改一下\\\" href='UpdateToolBoxAction?ToolBox_Id=\"+data.ToolboxArray[index].ToolBox_Id+\"'>添加</a></td>\";\r\n");
      out.write("\t\t\t\t\tvar s4=\"<td class=\\\"offAccount\\\"><a title=\\\"加入到当前诊断中\\\" href='javascript:void(0)' id=\"+data.ToolboxArray[index].ToolBox_Id+\" class='add'>添加</a></td></tr>\";\r\n");
      out.write("\t\t\t\t\tvar tr=$(s1+s2+s3+s4);\r\n");
      out.write("\t\t\t\t    tr.appendTo(\"#toolBoxList\");\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$('#toolBoxList').show();\r\n");
      out.write("\t\t\t\t $(\".add\").click(function (){\r\n");
      out.write("\t\t\t\t\t var ToolBox_Id = $(this).attr(\"id\");\r\n");
      out.write("\t\t\t\t\t $.ajax({\r\n");
      out.write("\t\t\t\t            url : '");
      out.print(templateUrl);
      out.write("/expe/ToolBoxForRead?ToolBox_Id='+ToolBox_Id,\r\n");
      out.write("\t\t\t\t            type : 'POST',\r\n");
      out.write("\t\t\t\t            contentType: \"application/x-www-form-urlencoded; charset=utf-8\", \r\n");
      out.write("\t\t\t\t\t\t    dataType : 'json',\r\n");
      out.write("\t\t\t\t\t\t    timeout : 8000,\r\n");
      out.write("\t\t\t\t\t\t    cache : true,\r\n");
      out.write("\t\t\t\t\t\t\terror : erryFunction, //错误执行方法  \r\n");
      out.write("\t\t\t\t\t\t\tsuccess : succFunction\t//成功执行方法  \r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\tfunction erryFunction() {alert(\"获取知识库出错，请重试!!\");}\r\n");
      out.write("\t\t\t\t\t\tfunction succFunction(data) {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#dialog\").dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#toolBoxList tr\").remove();\r\n");
      out.write("\t\t\t\t\t\t\tif($('#medical_advice').val()==\"\"){\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#medical_advice').val($('#medical_advice').val()+data.text_content);\r\n");
      out.write("\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#medical_advice').val($('#medical_advice').val()+\"、\"+data.text_content);\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t};\r\n");
      out.write("\t\t\t\t   });\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\t\r\n");
      out.write("function toolbox(){\r\n");
      out.write(" $(\"#dialog\").dialog(\"open\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("window.onload = function(){\r\n");
      out.write("\tif('");
      out.print(electronic_record);
      out.write("'!=\"\"){\r\n");
      out.write("\t\t\tgetElectronic_record('");
      out.print(electronic_record);
      out.write("');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tgetMidecalZheng('bz1.');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tgetMidecalDisease('zb1.');\r\n");
      out.write("\r\n");
      out.write("\t$('#dialog').dialog({\r\n");
      out.write("\t\t  open:function(){//对话框打开时初始化\r\n");
      out.write("\t\t\t  getToolBoxList();\r\n");
      out.write("\t\t  },\r\n");
      out.write("\t    autoOpen: false,\r\n");
      out.write("\t    height:480,\r\n");
      out.write("\t    width:850,\r\n");
      out.write("\t    modal:true,\r\n");
      out.write("\t    title:'我的知识库',\r\n");
      out.write("\t   draggable: false,\r\n");
      out.write("\t   buttons:[{\r\n");
      out.write("\t     text:\"关闭\",\r\n");
      out.write("\t     click:function(){\r\n");
      out.write("\t       $(this).dialog(\"close\");\r\n");
      out.write("\t     }\r\n");
      out.write("\t   }]\r\n");
      out.write("\t  });\t\r\n");
      out.write("};\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("   .offAccount a{ color:#0000ff;text-decoration:none;font-weight:bold}\r\n");
      out.write("   .offAccount a:hover{color:#ff0000}\r\n");
      out.write("   .offAccount a:active{color:#ff0000} \r\n");
      out.write(".ui-autocomplete {\r\n");
      out.write("    max-height: 200px;\r\n");
      out.write("    overflow-y: auto;\r\n");
      out.write("    /* prevent horizontal scrollbar */\r\n");
      out.write("    overflow-x: hidden;\r\n");
      out.write("    /* add padding to account for vertical scrollbar */\r\n");
      out.write("    padding-right: 20px;\r\n");
      out.write("}\r\n");
      out.write("/* IE 6 doesn't support max-height\r\n");
      out.write(" * we use height instead, but this forces the menu to always be this tall\r\n");
      out.write(" */\r\n");
      out.write("* html .ui-autocomplete {\r\n");
      out.write("    height: 100px;\r\n");
      out.write("}  \r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/topbar.jsp", out, false);
      out.write("\r\n");
      out.write("\t<div style=\"margin-left:300px;margin-top:10px\">\r\n");
      out.write("\t\t<p\r\n");
      out.write("\t\t\tstyle=\"background:url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/image/suggestionbg.png) no-repeat;font-size:18px;font-weight:400;width:600px\">\r\n");
      out.write("\t\t\t&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;患者信息：<label\r\n");
      out.write("\t\t\t\tid=\"username\"></label>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t   <div style=\"text-align:center\">\r\n");
      out.write("        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("           <a target=\"_blank\" href='expe/ArchInfoDetailForDoctorRead?electronic_record=");
      out.print(electronic_record);
      out.write("'><font size=\"4px\" color=\"#0000ff\">查看患者的电子健康病历</font></a>\r\n");
      out.write("       </div>\r\n");
      out.write("       \r\n");
      out.write("\t\t<div style=\"margin-top:10px\">\r\n");
      out.write("\t\t\t<div style=\"margin-left:30px;\">\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/image/angle_blue.png\" />&nbsp;&nbsp;&nbsp;&nbsp; <label\r\n");
      out.write("\t\t\t\t\tstyle=\"font-size:18px\">病情描述</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<textarea id=\"illn_desc\" name=\"illn_desc\"\r\n");
      out.write("\t\t\t\tstyle=\"width:720px;height:100px;overflow-y:scroll;resize:none;margin-left:30px;border:solid 2px #09F\"\r\n");
      out.write("\t\t\t\tdisabled=\"disabled\"></textarea>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<div style=\"margin-left:30px;float:left\">\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/image/angle_blue.png\" />&nbsp;&nbsp;&nbsp;&nbsp; <label\r\n");
      out.write("\t\t\t\t\tstyle=\"font-size:18px\">家族病史</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t<div style=\"float:none;margin-top:20px\">\r\n");
      out.write("\t\t\t\t<textarea id=\"fami_hist\" name=\"fami_hist\"\r\n");
      out.write("\t\t\t\t\tstyle=\"width:720px;height:100px;overflow-y:scroll;resize:none;margin-left:30px;border:solid 2px #09F\"\r\n");
      out.write("\t\t\t\t\tdisabled=\"disabled\"></textarea>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div style=\"margin-top:30px\">\r\n");
      out.write("\t\t\t<div style=\"margin-left:30px;float:left\">\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/image/angle_blue.png\" />&nbsp;&nbsp;&nbsp;&nbsp; <label\r\n");
      out.write("\t\t\t\t\tstyle=\"font-size:18px\">个人病史</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br /> <br />\r\n");
      out.write("\t\t\t<div style=\"float:none\">\r\n");
      out.write("\t\t\t\t<textarea id=\"pers_hist\" name=\"pers_hist\"\r\n");
      out.write("\t\t\t\t\tstyle=\"width:720px;height:100px;overflow-y:scroll;resize:none;margin-left:30px;border:solid 2px #09F\"\r\n");
      out.write("\t\t\t\t\tdisabled=\"disabled\"></textarea>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t<p\r\n");
      out.write("\t\t\t\tstyle=\"background:url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/image/suggestionbg.png) no-repeat;font-size:18px;font-weight:400;width:600px\">&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;专家诊断：</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<form action=\"DoctorOfflineConsultAction\"\r\n");
      out.write("\t\t\tname=\"DoctorOfflineConsultAction\" method=\"post\"\r\n");
      out.write("\t\t\tid=\"DoctorofflineConsult\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"electronic_record\" id=\"electronic_record\"\r\n");
      out.write("\t\t\t\tvalue=\"");
      out.print(electronic_record);
      out.write("\">\r\n");
      out.write("\t\t\t<div style=\"margin-left:30px;float:left\">\r\n");
      out.write("\t\t\t\t<div style=\"margin-top:4px;\">\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/image/angle_blue.png\" />&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t<label style=\"font-size:18px\">辩证结果</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<table style=\"margin-top:14px;font-size:18px;\"\r\n");
      out.write("\t\t\t\t\tborder=0 width=\"620\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>大类证名：</td>\r\n");
      out.write("\t\t\t\t\t\t<td><select id=\"first\"\r\n");
      out.write("\t\t\t\t\t\t\tonchange=\"getMidecalZheng(this.value);\" style=\"width:200px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"bz1.\" selected>基本虚证</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"bz2.\">基本实证</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"bz3.\">虚实夹杂证</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"bz4.\">心系证</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"bz5.\">肺系证</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"bz6.\">脾系证</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"bz7.\">肝系证</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"bz8.\">肾系证</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"bz9.\">脏腑兼证</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"bz10.\">卫表肌肤证</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"bz11.\">头面官窍证</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"bz12.\">经脉筋骨证</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"bz13.\">其他证</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"bz14.\">期、度、型</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>具体证名：</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"suggest1\" style=\"width:400px\" placeholder=\"请输入证名\"/></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"margin-left:30px;float:left\">\r\n");
      out.write("\t\t\t\t<div style=\"margin-top:20px;\">\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/image/angle_blue.png\" />&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t<label style=\"font-size:18px\">辨病结果</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<table style=\"margin-top:14px;font-size:18px;\"\r\n");
      out.write("\t\t\t\t\tborder=0 width=\"620\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>大类病名：</td>\r\n");
      out.write("\t\t\t\t\t\t<td><select id=\"firstDisease\"\r\n");
      out.write("\t\t\t\t\t\t\tonchange=\"getMidecalDisease(this.value);\" style=\"width:200px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"zb1.\" selected>传染病、寄生虫病</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"zb2.\">脑系病</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"zb3.\">心系病</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"zb4.\">肺系病</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"zb5.\">脾系病</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"zb6.\">肝系病</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"zb7.\">肾系病</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"zb8.\">男性前阴病类</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"zb9.\">颈瘿病类、乳房病类</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"zb10.\">疮疡病类</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"zb11.\">皮肤病类</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"zb12.\">妇女经、带、杂病类</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"zb13.\">胎、产及其疾病</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"zb14.\">新生儿病、小儿特发病</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"zb15.\">眼病类</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"zb16.\">耳鼻咽喉口齿病类</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"zb17.\">肛肠病类</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"zb18.\">躯体痹、痿、瘤等病类</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"zb19.\">时行病、中毒及其他病类</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"zb20.\">症状性名称</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"zb21.\">时行病、中毒及其他病类</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>具体病名：</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"suggest2\" style=\"width:400px\" placeholder=\"请输入病名\"/></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br /> <br /> <br /> <br />\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div style=\"margin-top:180px\">\r\n");
      out.write("\t\t\t\t<div style=\"margin-left:30px;float:left\">\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/image/angle_blue.png\" />&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t<label style=\"font-size:18px\">医疗建议</label>\r\n");
      out.write("\t\t\t\t\t<!-- 知识库关联专家工具箱 -->&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t<input id=\"expertToolbox\" name=\"expertToolbox\" type=\"button\" value=\"查看知识库\" onclick=\"toolbox();\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<br /> <br />\r\n");
      out.write("\t\t\t\t<div style=\"float:none\">\r\n");
      out.write("\t\t\t\t\t<textarea id=\"medical_advice\" name=\"medical_advice\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"width:720px;height:100px;overflow-y:scroll;resize:none;margin-left:30px;border:solid 2px #09F\"></textarea>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("            <ul id=\"fileList\" style=\"list-style:none;\"></ul>\r\n");
      out.write("\t\t\t<div style=\"margin-top:30px;height:150px;width:800px;\">\r\n");
      out.write("\t\t\t\t<div id=\"mysubmit\"\r\n");
      out.write("\t\t\t\t\tstyle=\"float:right;width:420px;margin-left:170px;\">\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/image/largebutton_subsave.png\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"checkSubmit();\" style=\"float:right;\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write(" <div id=\"dialog\" style=\"display: none\">\r\n");
      out.write("\t<div class=\"user_center_bigtitle\" style=\"text-align:center\"> <span><h3>我的知识库</h3></span> \r\n");
      out.write("   <hr></hr>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"my_dis_diray\">\r\n");
      out.write("\t\t<div class=\"my_dis_diray_con\">\r\n");
      out.write("\t\t\t<div class=\"mg_info\" style=\"font-family: KaiTi_GB2312;font-size: 18px;\">\r\n");
      out.write("\t\t\t\t\t<h3 style=\"text-align:center\">总共有（<a id=\"recAID\" href=\"javascript:void(0)\">0</a>）篇开方记录</h3>\r\n");
      out.write("\t\t\t\t<table id=\"toolBoxList\" width=\"700\" border=\"1\" id=\"table\" bordercolor=\"#FFFFFF\" align=\"center\" style=\"text-align: left;\">\r\n");
      out.write("                   </table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("  </div>\r\n");
      out.write("\t<!--版权信息等-->\r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/bottom/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
