package org.apache.jsp.WEB_002dINF.memb;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class expert_005frecommendation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");

String path = request.getContextPath();
String templateUrl = request.getScheme() + "://" + request.getHeader("host") +request.getContextPath();
request.setAttribute("url", templateUrl);
String search_str=new String(request.getParameter("search_str").getBytes("iso8859-1"),"utf-8");
String searchSelect=new String(request.getParameter("searchSelect").getBytes("iso8859-1"),"utf-8");
String username = session.getAttribute("username").toString();
//String search_str1=request.getParameter("search_str");

      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/core_head.jsp", out, false);
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"> \r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/topbarhead.jsp", out, false);
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/css/tab02.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/css/style.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/css/jquery.autocomplete.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/css/main.css\"/>\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/view/css/doctor.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/css/pagination.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/css/chat-2.0.css\" >\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/js/jquery.autocomplete.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/js/localdata.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/js/tab.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/js/jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/js/jquery.pagination.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/js/ajax-pushlet-client.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/css/chat-2.0.css\" />\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("        window.contextPath = \"");
      out.print(path);
      out.write("\";\r\n");
      out.write("        window[\"serverDomin\"] = \"larch\";\r\n");
      out.write(" </script>\r\n");
      out.write("\r\n");
      out.write(" <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/js/jsjac.js\"></script>\r\n");
      out.write(" <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/js/send.message.editor-1.0.js\"></script>\r\n");
      out.write(" <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/js/jquery.easydrag.js\"></script>\r\n");
      out.write(" <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/js/remote.jsjac.chat-2.0.js\"></script>\r\n");
      out.write(" <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/js/local.chat-2.0.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script charset=\"utf-8\"  type=\"text/javascript\">\r\n");
      out.write("var userchat ={\r\n");
      out.write("\t\tsender:'");
      out.print(username);
      out.write("',\r\n");
      out.write("\t\treciver:''\r\n");
      out.write("\t};\r\n");
      out.write("\t//在线聊天  \r\n");
      out.write("function chat(doctorName){\r\n");
      out.write("\t\talert(doctorName);\r\n");
      out.write("\t\tuserchat.reciver = doctorName;\r\n");
      out.write("\t  // var data=encodeURIComponent(JSON.stringify($('#input_doctor').val()),\"utf-8\");\r\n");
      out.write("\t  // alert(encodeURI(encodeURI($('#input_doctor').val())));//验证是否在线\r\n");
      out.write("\t    $.ajax({\r\n");
      out.write("\t                url : '");
      out.print(templateUrl);
      out.write("/CheckOnlineAction',\r\n");
      out.write("\t                type : 'POST',\r\n");
      out.write("\t                data: JSON.stringify(userchat),\r\n");
      out.write("\t                contentType: \"application/json; charset=utf-8\",  \r\n");
      out.write("\t\t\t\t\tdataType : 'text',\r\n");
      out.write("\t\t\t\t\ttimeout : 3000,\r\n");
      out.write("\t\t\t\t\tcache : true,\r\n");
      out.write("\t\t\t\t\tbeforeSend : LoadFunction, //加载执行方法  \r\n");
      out.write("\t\t\t\t\terror : erryFunction, //错误执行方法  \r\n");
      out.write("\t\t\t\t\tcomplete : conFunction,\r\n");
      out.write("\t\t\t\t\tsuccess : succFunction\t//成功执行方法  \r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\tfunction LoadFunction() {;}\r\n");
      out.write("\t\t\t\tfunction erryFunction() {alert(\"对方可能不在线，请重试!!\");}\r\n");
      out.write("\t     \t\tfunction conFunction()  {}\r\n");
      out.write("\t\t\t\tfunction succFunction(data) {\r\n");
      out.write("\t\t\t\t\talert(data);\r\n");
      out.write("\t\t\t\t\tvar data = String($.trim(data)); \r\n");
      out.write("\t\t\t\t\tif(data==\"no\"){\r\n");
      out.write("\t\t\t\t\t\talert(\"对方可能不在线，请重试！\");\r\n");
      out.write("\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tvar user={\r\n");
      out.write("\t        \t\t\t\tuserName:userchat.sender,\r\n");
      out.write("\t        \t\t\t\tpassword:\"987460880\"\r\n");
      out.write("\t        \t\t\t};\r\n");
      out.write("//\t\t\t\t\talert(userchat.reciver);\r\n");
      out.write("\t            \t//var userName = $(\":text[name='userName']\").val();\r\n");
      out.write("\t    \t\t\t// 登陆到openfire服务器\r\n");
      out.write("\t                 remote.jsjac.chat.login(user);\r\n");
      out.write("\t                // 建立一个聊天窗口应用，并设置发送者和消息接收者\r\n");
      out.write("\t                $.WebIM({\r\n");
      out.write("\t                    sender: userchat.sender,\r\n");
      out.write("\t                    receiver: userchat.reciver\r\n");
      out.write("\t                });\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\t\r\n");
      out.write("//筛选条件\r\n");
      out.write("var tiaojian = {\r\n");
      out.write("\t\"currProvince\":\"\",\r\n");
      out.write("\t\"currZhicheng\":\"\",\r\n");
      out.write("\t\"search_str\":\"");
      out.print(search_str);
      out.write("\",\r\n");
      out.write("\t\"pageIndex\":0\r\n");
      out.write("} ;\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\tif('");
      out.print(search_str);
      out.write("'!=\"\"){\r\n");
      out.write("\t\tbind(0);\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t//alert(data.innerHTML);\r\n");
      out.write("function getProvince(currProvince){\r\n");
      out.write("\ttiaojian.currProvince = currProvince;\r\n");
      out.write("\t bind(0);\r\n");
      out.write("}\r\n");
      out.write("function getZhicheng(currZhicheng){\r\n");
      out.write("\ttiaojian.currZhicheng = currZhicheng;\r\n");
      out.write("    bind(0);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function pageselectCallback(page_id,jq){\r\n");
      out.write("   bind(page_id);\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function bind(pageIndex){\r\n");
      out.write("\t//alert($('#input_doctor').val());\r\n");
      out.write("\t//alert(\"sd\");\r\n");
      out.write("  var total = 0;\r\n");
      out.write("  tiaojian.pageIndex = (pageIndex+1);\r\n");
      out.write("  // var data=encodeURIComponent(JSON.stringify($('#input_doctor').val()),\"utf-8\");\r\n");
      out.write("  // alert(encodeURI(encodeURI($('#input_doctor').val())));\r\n");
      out.write("  $.ajax({\r\n");
      out.write("    url : '");
      out.print(templateUrl);
      out.write("/DoctorServletAction',\r\n");
      out.write("    type : 'POST',\r\n");
      out.write("    data: JSON.stringify(tiaojian),\r\n");
      out.write("    contentType: \"application/json; charset=utf-8\", \r\n");
      out.write("\tdataType : 'json',\r\n");
      out.write("\ttimeout : 8000,\r\n");
      out.write("\tcache : true,\r\n");
      out.write("\tbeforeSend : LoadFunction, //加载执行方法  \r\n");
      out.write("\terror : erryFunction, //错误执行方法  \r\n");
      out.write("\tcomplete : conFunction,\r\n");
      out.write("\tsuccess : succFunction\r\n");
      out.write("\t\t\t//成功执行方法  \r\n");
      out.write("\t});\r\n");
      out.write("\tfunction LoadFunction() {\r\n");
      out.write("\t  // alert(\"dfdfd\");\r\n");
      out.write("\t\t// $(\".pager\").hide();\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction erryFunction() {\r\n");
      out.write("\t   alert(\"error\");\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction conFunction() {\r\n");
      out.write("\t\t// $(\".pager\").show();\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction succFunction(data) {\r\n");
      out.write("\t    alert(\"success\");\r\n");
      out.write("\t    $(\"#doctor_list\").html(\"\");\r\n");
      out.write("\t    var total = data.account;\r\n");
      out.write("\t    //alert(total);\r\n");
      out.write("\t   // alert(data.analyse);\r\n");
      out.write("\t    //$(\"#knowidArray\").html(\"<p>\"+data.knowidArray.knowCont+\"</p>\");\r\n");
      out.write("\t   // alert($(\"#analyse\").val());\r\n");
      out.write("\t   //$(\"#knowidArray\").html(\"<h3>\"+$('#input_doctor').val()+\"</h3><br>\");\r\n");
      out.write("\t  // $(\"#knowidArray\").html(\"\");\r\n");
      out.write("\t\t//$.each(data.jsonArray, function(index) {\r\n");
      out.write("\t\t//alert(\"each\");\r\n");
      out.write("\t\t  //alert(data.jsonArray[index].username);\r\n");
      out.write("\t     $.each(data.doctorArray, function(index) {\r\n");
      out.write("\t    \t var s1 = \"<div class=\\\"doc\\\"><div class=\\\"docpic\\\"><img src=\\\"image/headpic.png\\\" /></div> <div class=\\\"docinfo\\\"><p>\"+data.doctorArray[index].username+\"</p><p>\"+data.doctorArray[index].keshi+\"</p><p>\"+data.doctorArray[index].zhicheng+\"</p><p>\"+data.doctorArray[index].yiyuan+\"</p><p>\"+data.doctorArray[index].good+\"</p></div>\";\r\n");
      out.write("\t    \t var s2 = \"<div class=\\\"clear\\\"></div><div class=\\\"action\\\" ><div class=\\\"singleact\\\"> <img src=\\\"image/icon3.png\\\" /><br/><a href=\\\"javascript:void(0);\\\"  onclick=\\\"javascript:chat('\"+data.doctorArray[index].userId+\"');\\\">在线咨询</a><dd></dd></div>\";\r\n");
      out.write("\t    \t var s3 = \"<div class=\\\"singleact\\\"> <img src=\\\"image/icon4.png\\\" /><br/><a target=\\\"_blank\\\" href='user/addofflineConsultForm?doctorId=\"+data.doctorArray[index].userId+\"&doctorName=\"+data.doctorArray[index].username+\"'>离线咨询</a><dd></dd></div>\";\r\n");
      out.write("\t    \t //<form method=\\\"post\\\" name=\\\"addofflineConsultForm\\\" action=\\\"addofflineConsultForm  id=\\\"addofflineConsultForm\\\"><input type=\\\"hidden\\\" name=\\\"doctorName\\\" value=\"+data.doctorArray[index].username+\"/><a href=\\\"javascript:document.addofflineConsultForm.submit();\\\">离线咨询</a> </form>\r\n");
      out.write("\t    \t var s4 = \"<div class=\\\"singleact\\\"> <img src=\\\"image/icon1.png\\\" /><br/><a href=\\\"javascript:void(0);\\\"  onclick=\\\"javascript:collectExpert(this,'\"+data.doctorArray[index].userId+\"');\\\">\"+data.doctorArray[index].isCollect+\"</a><dd></dd></div>\";\r\n");
      out.write("\t    \t var s5 = \"<div class=\\\"singleact\\\"> <img src=\\\"image/icon5.png\\\" /><br/><a target=\\\"_blank\\\" href='user/yuyue?doctorId=\"+data.doctorArray[index].userId+\"&doctorName=\"+data.doctorArray[index].username+\"'>预约</a><dd></dd></div></div></div>\";\r\n");
      out.write("\t\t     $(\"#doctor_list\").html($(\"#doctor_list\").html()+s1+s2+s3+s4+s5);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//});\r\n");
      out.write("\t   $('#Pagination').pagination(total,{ //recordCount在后台定义的一个公有变量，通过从数据库查询记录进行赋值，返回记录的总数\r\n");
      out.write("\t       // recordCount: 30,   \r\n");
      out.write("            callback: pageselectCallback,  //点击分页时，调用的回调函数  \r\n");
      out.write("            prev_text: '« 上一页',  //显示上一页按钮的文本  \r\n");
      out.write("            next_text: '下一页 »',  //显示下一页按钮的文本  \r\n");
      out.write("            items_per_page:4,  //每页显示的项数  \r\n");
      out.write("            num_display_entries:14,  //分页插件中间显示的按钮数目  \r\n");
      out.write("            current_page:pageIndex,  //当前页索引  \r\n");
      out.write("            num_edge_entries:2 //分页插件左右两边显示的按钮数目  \r\n");
      out.write("        });  \r\n");
      out.write("   }\r\n");
      out.write("}\r\n");
      out.write("//预约\r\n");
      out.write("// function appointMentExpert(expeId){\r\n");
      out.write("// \talert(\"Sorry!\"+expeId+\"专家暂不接受预约!\");\r\n");
      out.write("// }\r\n");
      out.write("//收藏\r\n");
      out.write("function collectExpert(collect,expeId){\r\n");
      out.write("\talert(collect.innerHTML);\r\n");
      out.write("\tvar  collectData= String($.trim(collect.innerHTML)); \r\n");
      out.write("\t $.ajax({\r\n");
      out.write("         url : '");
      out.print(templateUrl);
      out.write("/CollectAction?collect='+collectData+'&userId='+expeId,\r\n");
      out.write("         type : 'POST',\r\n");
      out.write("         contentType: \"application/x-www-form-urlencoded; charset=utf-8\", \r\n");
      out.write("\t\t dataType : 'text',\r\n");
      out.write("\t\t timeout : 8000,\r\n");
      out.write("\t\t cache : true,\r\n");
      out.write("    \t error : erryFunction, //错误执行方法  \r\n");
      out.write("\t\t success : succFunction\t//成功执行方法  \r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tfunction erryFunction() {alert(collect.innerHTML+\"失败，请重试!!\");}\r\n");
      out.write("\t\tfunction succFunction(data) {\r\n");
      out.write("\t\t\tvar data = String($.trim(data)); \r\n");
      out.write("\t\t\tif(data=='yes'){\r\n");
      out.write("\t\t\t\talert(collect.innerHTML+\"成功!\");\r\n");
      out.write("\t\t\t  if(collect.innerHTML==\"收藏\")\r\n");
      out.write("\t\t\t\t   collect.innerHTML = \"取消收藏\";\r\n");
      out.write("\t\t\t\telse\r\n");
      out.write("\t\t\t\t\tcollect.innerHTML = \"收藏\";\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\talert(collect.innerHTML+\"失败，请重试!!\");\r\n");
      out.write("\t\t\t}\t\r\n");
      out.write("\t\t};\r\n");
      out.write("\t};\r\n");
      out.write("</script>\r\n");
      out.write("<title>网医-普通版</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/topbar.jsp", out, false);
      out.write("\r\n");
      out.write("<div class=\"clear\"></div>\r\n");
      out.write("<!--中上部分-->\r\n");
      out.write("<div id=\"middle\"> \r\n");
      out.write("  <!--左端logo-->\r\n");
      out.write("  <div id=\"leftMid\"> <img src=\"image/logo.png\" /> </div>\r\n");
      out.write("  <!--左端logo--> \r\n");
      out.write("  <!--右端输入框-->\r\n");
      out.write("  <div id=\"rightMid\">\r\n");
      out.write("    <form method=\"get\" id=\"searchForm\" >\r\n");
      out.write("      <br/>\r\n");
      out.write("      <input type=\"radio\" checked=\"checked\" name=\"searchSelect\" value=\"qiuyi\" />\r\n");
      out.write("      <label>求医</label>\r\n");
      out.write("      <input type=\"radio\"  name=\"searchSelect\" value=\"wenyao\"/>\r\n");
      out.write("      <label>问药</label>\r\n");
      out.write("      <input type=\"radio\" name=\"searchSelect\" value=\"yangsheng\" />\r\n");
      out.write("      <label>养生</label>\r\n");
      out.write("      <!--搜索-->\r\n");
      out.write("      <br/> <br/>\r\n");
      out.write("     <div id=\"searchIn\">\r\n");
      out.write("  \t<input type=\"text\" name=\"search_str\" id=\"search_str\"  maxlength=200 value=\"");
      out.print(search_str);
      out.write("\"/>\r\n");
      out.write("    <a href=\"javascript:void(0)\"> <img src=\"image/normalbutton_a.png\"/> </a> </div>\r\n");
      out.write("  \t  <input style=\"display:none\" />   \r\n");
      out.write("  \t </form>\r\n");
      out.write("  \t <div class=\"clear\"></div>\r\n");
      out.write("    \r\n");
      out.write("</div>\r\n");
      out.write("<!--右端输入框-->\r\n");
      out.write("</div>\r\n");
      out.write("<!--中上部分--> \r\n");
      out.write("<!--查询信息-->\r\n");
      out.write("\r\n");
      out.write("<div class=\"page\" >\r\n");
      out.write("  <ul class=\"tab\">\r\n");
      out.write("    <li id=\"tab_to_1\" ><a href=\"intelligent_query?search_str=");
      out.print(search_str);
      out.write("&searchSelect=");
      out.print(searchSelect);
      out.write("\" onclick=\"tab('tab',2,1)\" >智能咨询</a></li>\r\n");
      out.write("    <li id=\"tab_to_2\" class=\"no\"><a href=\"javascript:void(0)\" onclick=\"tab('tab',2,2)\" >专家推荐</a> </li>\r\n");
      out.write("  </ul>\r\n");
      out.write("  <div class=\"tab_mo\">\r\n");
      out.write("    <div id=\"tab_mo_1\" style=\"display:none\"></div>\r\n");
      out.write("    <div id=\"tab_mo_2\">\r\n");
      out.write("      <div class=\"history\">\r\n");
      out.write("        <ul class=\"h1\">\r\n");
      out.write("          <img src=\"image/icon2.png\" />\r\n");
      out.write("          <h3>历史</h3>\r\n");
      out.write("          <div class=\"clear\"></div>\r\n");
      out.write("          <li><a href=\"#\">张医师</a></li>\r\n");
      out.write("          <li><a href=\"#\">李医师</a></li>\r\n");
      out.write("          <li><a href=\"#\">刘医师</a></li>\r\n");
      out.write("          <li><a href=\"#\">蔡医师</a></li>\r\n");
      out.write("          <li><a href=\"#\">欧阳医师</a></li>\r\n");
      out.write("          <li><a href=\"#\">王医师</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <ul class=\"h2\">\r\n");
      out.write("          <img src=\"image/icon2.png\" />\r\n");
      out.write("          <h3>收藏</h3>\r\n");
      out.write("          <div class=\"clear\"></div>\r\n");
      out.write("          <li><a href=\"#\">张医师</a></li>\r\n");
      out.write("          <li><a href=\"#\">李医师</a></li>\r\n");
      out.write("          <li><a href=\"#\">刘医师</a></li>\r\n");
      out.write("          <li><a href=\"#\">蔡医师</a></li>\r\n");
      out.write("          <li><a href=\"#\">欧阳医师</a></li>\r\n");
      out.write("          <li><a href=\"#\">王医师</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-----end history------>\r\n");
      out.write("      <div id=\"innertab\">\r\n");
      out.write("        <div class=\"tabbtn active\">专家推荐</div>\r\n");
      out.write("        <!--<div class=\"tabbtn\">离线专家</div>-->\r\n");
      out.write("        <div id=\"tabcont\">\r\n");
      out.write("          <p style=\"float:left;margin: 0;padding: 25px 0 0 30px;font-size: 16px;\">综合排列</p>\r\n");
      out.write("          \r\n");
      out.write("          <div id=\"choose\" style=\"height: 28px\">\r\n");
      out.write("           <select id=\"selProvince\"onChange= \"getProvince(this.options[this.selectedIndex].value)\">\r\n");
      out.write("              <option value=\"\">-按地区-</option>\r\n");
      out.write("              <option value=\"湖南\">湖南</option>\r\n");
      out.write("              <option value=\"河南\">河南</option>\r\n");
      out.write("               <option value=\"北京\">北京</option>\r\n");
      out.write("           </select>\r\n");
      out.write("            <select id=\"selZhicheng\"onChange= \"getZhicheng(this.options[this.selectedIndex].value)\">\r\n");
      out.write("              <option value=\"\">-按职称-</option>\r\n");
      out.write("              <option value=\"主任医师\">主任医师</option>\r\n");
      out.write("              <option value=\"副主任医师\">副主任医师</option>\r\n");
      out.write("              <option value=\"主治医师\">主治医师</option>\r\n");
      out.write("              <option value=\"住院医师\">住院医师</option>\r\n");
      out.write("           </select>\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("           </div> \r\n");
      out.write("          <div class=\"clear\"></div> \r\n");
      out.write("          <div id=\"doctor_list\" class=\"container\">    </div><br/>\r\n");
      out.write("          <div id = \"Pagination\" class = \"megas512\" > </div>\r\n");
      out.write("        <!------end tabcont--------> \r\n");
      out.write("      </div>\r\n");
      out.write("      <!----------end innertab-----------> \r\n");
      out.write("    </div>\r\n");
      out.write("    <!-------end tab_mo_2---------> \r\n");
      out.write("  </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!--------end tab_mo----------->\r\n");
      out.write("</div>\r\n");
      out.write("<!-------end page-------->\r\n");
      out.write("<!-- 日志信息 -->\r\n");
      out.write("    <div id=\"error\" style=\"display:none ; background-color: red;\"></div>\r\n");
      out.write("    <div id=\"info\" style=\"display:none ; background-color: #999999;\"></div>\r\n");
      out.write("    <!-- 聊天来消息提示 -->\r\n");
      out.write("    \r\n");
      out.write("<div class=\"clear\"></div>  \r\n");
      out.write("<div id=\"footer\">\r\n");
      out.write(" <div class=\"chat-message\" >\r\n");
      out.write("        <img src=\"images/write_icon.png\" class=\"no-msg\"/>\r\n");
      out.write("        <img src=\"images/write_icon.gif\" class=\"have-msg\" style=\"display: none;\"/>\r\n");
      out.write("    </div>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/bottom/footer.jsp", out, false);
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
